import React, { useEffect, useMemo, useState } from 'react';
import { doc, onSnapshot, setDoc } from 'firebase/firestore';
import { onAuthStateChanged, sendPasswordResetEmail, signInWithEmailAndPassword, signOut } from 'firebase/auth';
import { getDownloadURL, ref, uploadBytes } from 'firebase/storage';
import { auth, db, storage } from './firebase';
import { DEFAULT_TOTAL_SENSORS, PRIMARY_ADMIN_EMAIL, REPORT_DOC_PATH, USER_ROLES, categories, hardwareIssueTypes, severityOrder, createDeepDiveTemplate } from './constants';
import { Header, ShiftInfoCard, AddAlarmCard, SensorHealthCard, HardwareIssuesTable, DTWTable, ActiveAlarmsTable } from './components/Sections';
import { LoginModal, AdminManagerModal } from './components/Modals';

export default function ShiftReportDashboard() {
  const [currentUser,setCurrentUser]=useState({name:'Guest Viewer',email:'',role:USER_ROLES.VIEWER});
  const [isEditMode,setIsEditMode]=useState(false),[showLogin,setShowLogin]=useState(false),[showAdminManager,setShowAdminManager]=useState(false);
  const [loginEmail,setLoginEmail]=useState(''),[loginPassword,setLoginPassword]=useState(''),[loginError,setLoginError]=useState('');
  const [approvedAdmins,setApprovedAdmins]=useState([]),[newAdminEmail,setNewAdminEmail]=useState(''),[adminAccessMessage,setAdminAccessMessage]=useState('');
  const [reportInfo,setReportInfo]=useState({date:new Date().toISOString().split('T')[0],summary:''});
  const [alarms,setAlarms]=useState([]),[scheduledDTW,setScheduledDTW]=useState([]);
  const [newAlarm,setNewAlarm]=useState({asset:'',component:'',issue:'',category:'Critical'});
  const [newDTW,setNewDTW]=useState({category:'Critical',asset:'',component:'',issue:'',customIssue:'',repairNotes:''});
  const [searchTerm,setSearchTerm]=useState(''),[categoryFilter,setCategoryFilter]=useState('All'),[lastSaved,setLastSaved]=useState('Not saved yet');
  const [saveMessage,setSaveMessage]=useState(''),[alarmEntryMessage,setAlarmEntryMessage]=useState(''),[snapshotUploadMessage,setSnapshotUploadMessage]=useState('');

  const isPrimaryAdmin=currentUser.email?.toLowerCase()===PRIMARY_ADMIN_EMAIL.toLowerCase();
  const canEdit=currentUser.role===USER_ROLES.ADMIN||isPrimaryAdmin;

  useEffect(()=>{const unsub=onSnapshot(doc(db,...REPORT_DOC_PATH),snap=>{if(!snap.exists()){setLastSaved('No cloud report saved yet');return;}const d=snap.data();setReportInfo(d.reportInfo||{date:new Date().toISOString().split('T')[0],summary:''});setAlarms(d.alarms||[]);setScheduledDTW(d.scheduledDTW||[]);setApprovedAdmins(d.approvedAdmins||[]);setLastSaved(d.lastSaved||'Recovered cloud report');},err=>{console.error('Cloud report load failed:',err);setSaveMessage('Cloud report could not be loaded. Check Firebase Firestore rules.');setTimeout(()=>setSaveMessage(''),6000);});return()=>unsub();},[]);
  useEffect(()=>{const unsub=onAuthStateChanged(auth,u=>{if(!u?.email){setCurrentUser({name:'Guest Viewer',email:'',role:USER_ROLES.VIEWER});setIsEditMode(false);return;}const email=u.email.toLowerCase();const admin=email===PRIMARY_ADMIN_EMAIL.toLowerCase()||approvedAdmins.some(a=>a.email===email);setCurrentUser({name:email,email,role:admin?USER_ROLES.ADMIN:USER_ROLES.VIEWER});setIsEditMode(admin);});return()=>unsub();},[approvedAdmins]);

  const handleLogin=async()=>{const email=loginEmail.trim().toLowerCase();if(!email||!loginPassword){setLoginError('Enter your email and password.');return;}if(email!==PRIMARY_ADMIN_EMAIL.toLowerCase()&&!approvedAdmins.some(a=>a.email===email)){setLoginError('This email is not approved for admin access.');return;}try{await signInWithEmailAndPassword(auth,email,loginPassword);setShowLogin(false);setLoginEmail('');setLoginPassword('');setLoginError('');}catch(e){console.error('Firebase login failed:',e);setLoginError(e.code==='auth/unauthorized-domain'?'This Netlify domain is not authorized in Firebase Authentication settings.':'Unable to login with Firebase. Check email/password.');}};
  const handleLogout=async()=>{await signOut(auth);setCurrentUser({name:'Guest Viewer',email:'',role:USER_ROLES.VIEWER});setIsEditMode(false);setShowAdminManager(false);setShowLogin(false);};
  const saveDashboard=async()=>{if(!canEdit){setSaveMessage('Only an admin can save the shift report.');setTimeout(()=>setSaveMessage(''),5000);return;}const t=new Date().toLocaleString();try{await setDoc(doc(db,...REPORT_DOC_PATH),{reportInfo,alarms,scheduledDTW,approvedAdmins,lastSaved:t,updatedBy:currentUser.email||'Unknown admin',updatedAt:t},{merge:true});setLastSaved(t);setSaveMessage('Report saved to Firebase. The latest shift report will now load on other computers.');setTimeout(()=>setSaveMessage(''),5000);}catch(e){console.error('Cloud save failed:',e);setSaveMessage('Cloud save failed. Check Firebase Firestore rules and Netlify environment variables.');setTimeout(()=>setSaveMessage(''),6000);}};
  const grantAdminAccess=async()=>{const email=newAdminEmail.trim().toLowerCase();if(!isPrimaryAdmin){setAdminAccessMessage('Only the primary admin can grant admin access.');return;}if(!email||!email.includes('@')){setAdminAccessMessage('Enter a valid email address.');return;}if(approvedAdmins.some(a=>a.email===email)){setAdminAccessMessage('This user is already approved.');return;}const updated=[...approvedAdmins,{email,role:USER_ROLES.ADMIN,approvedAt:new Date().toLocaleString()}];try{setApprovedAdmins(updated);await setDoc(doc(db,...REPORT_DOC_PATH),{approvedAdmins:updated},{merge:true});setNewAdminEmail('');setAdminAccessMessage(`${email} approved. Create this user in Firebase Authentication if needed, then click Send Setup Email.`);}catch(e){console.error(e);setAdminAccessMessage('Admin approval could not be saved to Firebase. Check Firestore rules.');}};
  const removeAdminAccess=async(email)=>{const updated=approvedAdmins.filter(a=>a.email!==email);setApprovedAdmins(updated);await setDoc(doc(db,...REPORT_DOC_PATH),{approvedAdmins:updated},{merge:true});};
  const sendPasswordSetupEmail=async(email)=>{try{await sendPasswordResetEmail(auth,email);setAdminAccessMessage(`Firebase password setup/reset email sent to ${email}.`);}catch(e){console.error(e);setAdminAccessMessage(e.code==='auth/user-not-found'?`${email} is approved, but no Firebase Authentication account exists yet. Create this user in Firebase Authentication first, then send the setup email again.`:'Password setup email failed. Check Firebase Authentication email settings and authorized domains.');}};
  const exportToPDF=()=>window.print();
  const addAlarm=()=>{if(!canEdit||!isEditMode){setAlarmEntryMessage('Edit Mode must be enabled before adding an alarm.');return;}if(!newAlarm.asset.trim()){setAlarmEntryMessage('Enter an Asset / Conveyor ID before adding an alarm.');return;}if(!newAlarm.issue){setAlarmEntryMessage('Select an Issue Description before adding an alarm.');return;}setAlarms([...alarms,{...newAlarm,id:Date.now(),status:'Open',createdAt:new Date().toLocaleString(),acknowledgedAt:'',resolvedAt:'',showDetails:false,deepDive:createDeepDiveTemplate()}]);setNewAlarm({asset:'',component:'',issue:'',category:'Critical'});setAlarmEntryMessage('Alarm added. Click Save Report to save your changes.');setTimeout(()=>setAlarmEntryMessage(''),4000);};
  const addDTWRepair=()=>{const issue=newDTW.issue==='Custom'?newDTW.customIssue:newDTW.issue;if(!newDTW.asset||!issue||!canEdit||!isEditMode)return;setScheduledDTW([...scheduledDTW,{...newDTW,issue,customIssue:'',id:Date.now()}]);setNewDTW({category:'Critical',asset:'',component:'',issue:'',customIssue:'',repairNotes:''});};
  const updateDTWRepair=(id,field,value)=>setScheduledDTW(scheduledDTW.map(r=>r.id===id?{...r,[field]:value}:r));
  const removeDTWRepair=id=>setScheduledDTW(scheduledDTW.filter(r=>r.id!==id));
  const removeAlarm=id=>setAlarms(alarms.filter(a=>a.id!==id));
  const toggleAlarmDetails=id=>setAlarms(alarms.map(a=>a.id===id?{...a,showDetails:!a.showDetails}:a));
  const updateAlarmField=(id,field,value)=>setAlarms(alarms.map(a=>{if(a.id!==id)return a;const u={[field]:value};if(field==='status'&&value==='Acknowledged')u.acknowledgedAt=new Date().toLocaleString();if(field==='status'&&value==='Resolved'){u.resolvedAt=new Date().toLocaleString();u.showDetails=false;}return{...a,...u};}));
  const updateAlarmDeepDive=(id,field,value)=>setAlarms(alarms.map(a=>a.id===id?{...a,deepDive:{...a.deepDive,[field]:value}}:a));
  const uploadSensorSnapshot=async(id,event)=>{const file=event.target.files?.[0];event.target.value='';if(!file)return;if(!canEdit||!isEditMode){setSnapshotUploadMessage('Edit Mode must be enabled before uploading a sensor snapshot.');setTimeout(()=>setSnapshotUploadMessage(''),5000);return;}try{setSnapshotUploadMessage('Uploading sensor data snapshot...');const safe=file.name.replace(/[^a-zA-Z0-9._-]/g,'_');const path=`sensorSnapshots/${id}/${Date.now()}-${safe}`;const snapRef=ref(storage,path);await uploadBytes(snapRef,file);const url=await getDownloadURL(snapRef);const img={id:`${id}-${Date.now()}`,name:file.name,url,path,uploadedAt:new Date().toLocaleString(),uploadedBy:currentUser.email||'Unknown admin'};setAlarms(cur=>cur.map(a=>a.id===id?{...a,deepDive:{...a.deepDive,images:[...(a.deepDive.images||[]),img]}}:a));setSnapshotUploadMessage('Sensor data snapshot uploaded. Click Save Report to save it for other computers.');setTimeout(()=>setSnapshotUploadMessage(''),6000);}catch(e){console.error(e);setSnapshotUploadMessage('Snapshot upload failed. Check Firebase Storage rules and Netlify environment variables.');setTimeout(()=>setSnapshotUploadMessage(''),6000);}};
  const removeSensorSnapshot=(id,imgId)=>{setAlarms(cur=>cur.map(a=>a.id===id?{...a,deepDive:{...a.deepDive,images:(a.deepDive.images||[]).filter(i=>i.id!==imgId)}}:a));setSnapshotUploadMessage('Snapshot removed from report. Click Save Report to save this change.');setTimeout(()=>setSnapshotUploadMessage(''),5000);};

  const activeAlarmCount=alarms.filter(a=>a.status!=='Resolved').length;
  const normalSensorCount=Math.max(DEFAULT_TOTAL_SENSORS-activeAlarmCount,0);
  const activeAlarmPercent=((activeAlarmCount/DEFAULT_TOTAL_SENSORS)*100).toFixed(2);
  const normalSensorPercent=((normalSensorCount/DEFAULT_TOTAL_SENSORS)*100).toFixed(2);
  const countByCategory=cat=>alarms.filter(a=>a.category===cat&&a.status!=='Resolved').length;
  const sensorHealthData=[{name:'Critical',value:Math.max(countByCategory('Critical'),2),realValue:countByCategory('Critical'),fill:'#dc2626'},{name:'High',value:Math.max(countByCategory('High'),2),realValue:countByCategory('High'),fill:'#f97316'},{name:'Standard',value:Math.max(countByCategory('Standard'),2),realValue:countByCategory('Standard'),fill:'#eab308'},{name:'Hardware Issue',value:Math.max(countByCategory('Hardware Issue'),2),realValue:countByCategory('Hardware Issue'),fill:'#2563eb'},{name:'Normal Sensors',value:Math.max(normalSensorCount*0.08,10),realValue:normalSensorCount,fill:'#22c55e'}];
  const hardwareIssueCounts=useMemo(()=>hardwareIssueTypes.reduce((acc,type)=>({...acc,[type]:alarms.filter(a=>a.category==='Hardware Issue'&&a.status!=='Resolved'&&a.issue===type).length}),{}),[alarms]);
  const totalHardwareIssues=useMemo(()=>hardwareIssueTypes.reduce((t,type)=>t+(hardwareIssueCounts[type]||0),0),[hardwareIssueCounts]);
  const filteredAlarms=useMemo(()=>alarms.filter(a=>{if(a.category==='Hardware Issue')return false;const s=searchTerm.toLowerCase();return (a.asset.toLowerCase().includes(s)||a.issue.toLowerCase().includes(s)||(a.component||'').toLowerCase().includes(s)||(a.deepDive?.location||'').toLowerCase().includes(s))&&(categoryFilter==='All'||a.category===categoryFilter);}).sort((a,b)=>severityOrder[a.category]-severityOrder[b.category]||new Date(b.createdAt)-new Date(a.createdAt)),[alarms,searchTerm,categoryFilter]);
  const sortedScheduledDTW=useMemo(()=>[...scheduledDTW].sort((a,b)=>severityOrder[a.category]-severityOrder[b.category]||String(a.asset).localeCompare(String(b.asset))),[scheduledDTW]);

  return <div className="min-h-screen bg-slate-100 p-6 print:bg-white print:p-2"><div className="max-w-7xl mx-auto space-y-6"><Header currentUser={currentUser} isEditMode={isEditMode} setIsEditMode={setIsEditMode} canEdit={canEdit} isPrimaryAdmin={isPrimaryAdmin} setShowLogin={setShowLogin} setShowAdminManager={setShowAdminManager} handleLogout={handleLogout} saveDashboard={saveDashboard} exportToPDF={exportToPDF} lastSaved={lastSaved}/>{saveMessage&&<div className="rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-2 text-sm text-emerald-700">{saveMessage}</div>}{snapshotUploadMessage&&<div className="rounded-xl border border-sky-200 bg-sky-50 px-4 py-2 text-sm text-sky-700">{snapshotUploadMessage}</div>}<div className="grid grid-cols-1 md:grid-cols-2 gap-6"><ShiftInfoCard reportInfo={reportInfo} setReportInfo={setReportInfo} isEditMode={isEditMode}/><AddAlarmCard canEdit={canEdit} isEditMode={isEditMode} newAlarm={newAlarm} setNewAlarm={setNewAlarm} addAlarm={addAlarm} alarmEntryMessage={alarmEntryMessage}/></div><SensorHealthCard sensorHealthData={sensorHealthData} activeAlarmCount={activeAlarmCount} normalSensorCount={normalSensorCount} activeAlarmPercent={activeAlarmPercent} normalSensorPercent={normalSensorPercent}/><HardwareIssuesTable hardwareIssueCounts={hardwareIssueCounts} totalHardwareIssues={totalHardwareIssues}/><DTWTable isEditMode={isEditMode} canEdit={canEdit} newDTW={newDTW} setNewDTW={setNewDTW} addDTWRepair={addDTWRepair} sortedScheduledDTW={sortedScheduledDTW} updateDTWRepair={updateDTWRepair} removeDTWRepair={removeDTWRepair}/><ActiveAlarmsTable filteredAlarms={filteredAlarms} countByCategory={countByCategory} categoryFilter={categoryFilter} setCategoryFilter={setCategoryFilter} searchTerm={searchTerm} setSearchTerm={setSearchTerm} isEditMode={isEditMode} canEdit={canEdit} toggleAlarmDetails={toggleAlarmDetails} removeAlarm={removeAlarm} updateAlarmDeepDive={updateAlarmDeepDive} updateAlarmField={updateAlarmField} uploadSensorSnapshot={uploadSensorSnapshot} removeSensorSnapshot={removeSensorSnapshot}/><LoginModal showLogin={showLogin} loginEmail={loginEmail} setLoginEmail={setLoginEmail} loginPassword={loginPassword} setLoginPassword={setLoginPassword} loginError={loginError} setLoginError={setLoginError} setShowLogin={setShowLogin} handleLogin={handleLogin}/><AdminManagerModal showAdminManager={showAdminManager} setShowAdminManager={setShowAdminManager} newAdminEmail={newAdminEmail} setNewAdminEmail={setNewAdminEmail} grantAdminAccess={grantAdminAccess} adminAccessMessage={adminAccessMessage} setAdminAccessMessage={setAdminAccessMessage} approvedAdmins={approvedAdmins} sendPasswordSetupEmail={sendPasswordSetupEmail} removeAdminAccess={removeAdminAccess}/></div></div>;
}
